$engine: 3
$onesync: on
name: Basic FiveM Setup Recipe with included scripts
version: 1
author: Mrtylergamer
description: Basic Recipe Including DpEmotes, Luxart Vehicle Control, vMenu to make the developers job Easier (Hopefully)

tasks: 
  # Download default CFX resources 
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources
    
