$onesync: on
name: Basic FiveM Setup Recipe with included scripts
version: v1.0.0
author: Mrtylergamer
description: "Recipe for the developer who doesn't want to set up a server the same way 30 times."

variables: 
    LVC-ID: Change-Me

tasks: 
  # Download default CFX resources 
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources
    
  - action: download_file
    url: https://raw.githubusercontent.com/error-reporter-cmd/FiveM-setup-Recipe/main/server.cfg
    path: ./server.cfg
    
  # Download vMenu
  - action: download_file
    url: https://github.com/TomGrobbe/vMenu/releases/download/v3.5.0/vMenu-v3.5.0.zip
    path: ./tmp/vMenu-v3.5.zip
  
 # Unzips and places vMenu on resources folder 
  - action: unzip
    src: ./tmp/vMenu-v3.5.zip
    dest: ./resources/vMenu
    
  - action: move_path
    src: ./resources/vMenu/config/permissions.cfg
    dest: ./permissions.cfg

  - action: download_github
    src: https://github.com/TayMcKenzieNZ/dpemotes
    ref: master
    dest: ./resources/[scripts]/dpemotes
  
  - action: replace_string
    file: ./resources/[scripts]/dpemotes/config.lua
    search: 'AdultEmotesDisabled = false,'
    replace: 'AdultEmotesDisabled = true,'
  
    # Download lvc
  - action: download_file
    url: https://github.com/TrevorBarns/luxart-vehicle-control/releases/download/3.2.9/Luxart.Vehicle.Control.v3.2.9-Rev1.zip
    path: ./tmp/lvc.zip
      
     # Unzips and places vMenu on resources folder 
  - action: unzip
    src: ./tmp/lvc.zip
    dest: ./tmp/lvc
    
  - action: move_path
    src: ./tmp/lvc/dependencies/RageUI/
    dest: ./resources/[scripts]/RageUI

  - action: move_path
    src: ./tmp/lvc/lvc
    dest: ./resources/[scripts]/lvc
    overwrite: true
    
  - action: replace_string
    file: ./resources/[scripts]/lvc/SETTINGS.lua
    search: 'community_id = ""'
    replace: 'community_id = "{{LVC-ID}}"'
    
  - action: replace_string
    file: ./resources/[scripts]/lvc/SETTINGS.lua
    search: 'park_kill_default = false'
    replace: 'park_kill_default = true'
    
