$engine: 3
$onesync: on
name: FiveM Setup
version: v1.1.0
author: Mrtylergamer
description: Basic Recipe Including DpEmotes, Luxart Vehicle Control, vMenu to make the developers job Easier (Hopefully)

tasks: 
  # Download default CFX resources 
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources
    
 - action: download_file
    url: https://raw.githubusercontent.com/error-reporter-cmd/FiveM-Recipe-Including-Vmenu-essentials/main/server.cfg
    path: ./server.cfg
    
  # Download vMenu
  - action: download_file
    url: https://github.com/TomGrobbe/vMenu/releases/download/v3.5.0/vMenu-v3.5.0.zip
    path: ./tmp/vMenu-v3.5.zip
  
 # Unzips and places vMenu on resources folder 
 - action: unzip
   src: ./tmp/vMenu-v3.5.zip
   dest: ./resources/vMenu

- action: download_github
  src: TayMcKenzieNZ/dpemotes
  dest: ./resources/[scripts]/dpemotes
  
- action: replace_string
  file: ./resources/[scripts]/dpemotes/config.lua
  search: 'AdultEmotesDisabled = false,'
  replace: 'AdultEmotesDisabled = true,'
  

